FROM node:10.15.3-alpine

LABEL "maintainer": "adam@adamjberkowitz.com" \
      "name": "Adam Berkowitz" \
      "project": "node base"

WORKDIR /project

COPY ./node/entrypoint.sh /entrypoint.sh
COPY ./node/wait-for-it.sh /project/wait-for-it.sh

RUN apk update && apk add bash \
  && chmod +x /entrypoint.sh \
  && chmod +x /project/wait-for-it.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]