FROM node:8.10.0-alpine

LABEL "maintainer": "adam@adamjberkowitz.com" \
      "name": "Adam Berkowitz" \
      "project": "node base"

WORKDIR /project

COPY ./node/entrypoint.sh /entrypoint.sh

RUN apk update && apk add bash \
  && chmod +x /entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]